language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t plato28/docker-reactwo -f Dockerfile.dev .

script:
  - docker run -e CI=true plato28/docker-reactwo npm run test
